Bookstore Milestone 5
t-yanick/react-bookstore pull request #5
Opened 2021-06-06 10:02 UTC by t-yanick

In this PR we,
- Implemented styling of the various components based on the design provided at [this Zeplin Project](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378)

Your kind review and feedback will help in improving the project.
**TAZOH Yanick TAZOH**
@t-yanick

2021-06-06 20:11 UTC, Berabjesus requested changes
# Status: CHANGES REQUIRED :warning: :construction: 
Hey @t-yanick! Congratulations on getting this far. You have done a remarkable job with this project. 👏

### However, we need to take a step back and check out some CSS bad practices on this milestone.

- [ ] In the stylesheets of the app, make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright). One requirement in this milestone is t avoid repeating the same rule. Please have a look at your CSS and refactor the duplicated rules. Have a look at the inline comments below.

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-06-06 20:11 UTC, Berabjesus commented on src/components/App.css
> +  display: flex;
- [ ] As an example here `display: flex;` is used on 11 different places. Kindly create a class for it and call it the react component when needed.

2021-06-06 20:11 UTC, Berabjesus commented on src/components/App.css
> +  justify-content: space-around;
- [ ] `justify-content: space-around;` is used 6 different places. Kindly do the same for this and other duplicated rules.

2021-06-07 09:56 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-06-07 14:25 UTC, merged